name: Game Documentation
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docs:
    runs-on: windows-latest
    steps:
      - name: Check Installed Software
        run: where git & where python & where pip
        shell: cmd
        
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Conan
        run: pip install conan
        
      - name: Detect profile
        run: conan profile detect --force
        
      - name: Install tool dependencies
        run: conan install devops/docs --build=missing -of=devops/docs/build --profile:host=default --profile:build=default

      - name: Show conanrun.bat contents
        run: type devops\docs\build\conanrun.bat
        shell: cmd

      - name: Inspect runenv file
        run: type devops\docs\build\conanrunenv-release-x86_64.bat
        shell: cmd
      
      - name: Run Doxygen with activated Conan environment
        shell: cmd
        run: |
          call devops\docs\build\conanrun.bat
          doxygen devops\docs\Doxyfile
        
      - name: Upload Docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: Documentation\html
        
      - name: Setup Pages
        run: echo "Setup Pages"

      - name: Deploy to GitHub Pages
        run: echo "Deploy to GitHub Pages"        
