name: Game Documentation
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docs:
    runs-on: windows-latest
    steps:
      - name: Check Installed Software
        run: where git & where python & where pip
        shell: cmd
        
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Conan
        run: pip install conan==2.3.2

      - name: Check Conan version
        run: conan --version
        
      - name: Detect profile
        run: conan profile detect --force
        
      - name: Install tool dependencies
        run: conan install devops/docs --build=missing

      - name: Run Doxygen
        run: conan run doxygen devops/docs/Doxyfile
        
      - name: Upload Docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: Documentation\html
        
      - name: Setup Pages
        run: echo "Setup Pages"

      - name: Deploy to GitHub Pages
        run: echo "Deploy to GitHub Pages"        
